<?php

namespace AppBundle\Repository;

/**
 * ClientinformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientinformationRepository extends \Doctrine\ORM\EntityRepository
{
}
