<?php

namespace AppBundle\Repository;

/**
 * TypeprofessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeprofessionRepository extends \Doctrine\ORM\EntityRepository
{
}
