<?php

namespace AppBundle\Repository;

/**
 * UserinformationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserinformationsRepository extends \Doctrine\ORM\EntityRepository
{
}
