contra_index:
    path:     /
    defaults: { _controller: "AppBundle:Typecontrat:index" }
    methods:  GET

contra_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Typecontrat:show" }
    methods:  GET

contra_new:
    path:     /new
    defaults: { _controller: "AppBundle:Typecontrat:new" }
    methods:  [GET, POST]

contra_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Typecontrat:edit" }
    methods:  [GET, POST]

contra_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Typecontrat:delete" }
    methods:  DELETE
