profession_index:
    path:     /
    defaults: { _controller: "AppBundle:Typeprofession:index" }
    methods:  GET

profession_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Typeprofession:show" }
    methods:  GET

profession_new:
    path:     /new
    defaults: { _controller: "AppBundle:Typeprofession:new" }
    methods:  [GET, POST]

profession_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Typeprofession:edit" }
    methods:  [GET, POST]

profession_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Typeprofession:delete" }
    methods:  DELETE
